# Prework Assignment

### General Background Questions

1. Why is version control important in science?

As experiments and lab work and research now can involve massive data points and lots of collaboration, it is really important that sharing and accessing work is efficient. Git helps do this with version control- allowing sharing of a lab file/notebook for example, allowing commits and collaboration and edits from a whole team. Git also makes sure there are multiple version backups in case of a mistake or need to merge previous work with current discoveries. It also gives freedom for certain members to try their own methods and revert if needed so git promotes an innovative environment.

2. What kind of research artifacts can we track with Git?

Git can track various files from manuscripts/notes and large data sets to generated algorithms and statistical analyses/models. 

3. What are the three main things that can go wrong in a data science project?

1. The data is not of the form or does not contain what you expected or wanted. 
2. The model doesn't work out because of the probability distribution/accuracy. Not strong enough of a correlation/signal.
3. The problem thought to be needing solving wasn't the right problem to tackle. 

### Python Background Questions

These short exercises are a way to familiarize yourself with python. If you find these exercises too difficult, don’t worry! We will review the basics the first day to make sure we are all comfortable coding in Python.

Please save your work in this document and `git push` them to the `prework-assignment` repo.

----------------------------------------------------------------

### Problem 1: Basic Operations

You are at Vanessa's Vegan Cafe and you loved it so much you wanna leave a tip. Write a function that takes the amount owed and calculates how much money you pay with an 18% tip. If functions still scare you, just the solution code will do.

In [11]:
def tip_calculator(amt_owed): 
    tip = amt_owed * 1.18
    return tip 

In [12]:
#check: print(tip_calculator(10))

----------------------------------------------------------------

### Problem 2: Lists

I have a fortune cookie that says my lucky numbers are:

       [23, 54, 6, 8, 10078, 3]

Write a function that returns 3 lists (if functions still scare you, just the solution code will do)
   - replace the number 6 with 1
   - the above list in decreasing order
   - all values greater than 15

In [22]:
def three_lists(lst): 
    new_lst = []
    replace_lst1 = lst[:]
    replace_lst1[2] = 1; 
    new_lst.append(replace_lst1)
    decr_lst2 = lst[:]
    decr_lst2.sort(reverse = True)
    new_lst.append(decr_lst2)
    gr15_lst3 = [i for i in lst if i > 15]
    new_lst.append(gr15_lst3)
    return new_lst

----------------------------------------------------------------

In [24]:
#check three_lists print(three_lists([23, 54, 6, 8, 10078, 3]))

### Problem 3: Basic Operations

Let's now take the first step in coding some real data science. Write a statement that loads the `numpy` library into the interpreter and gives it an alias of `np`.

In [25]:
import numpy as np

----------------------------------------------------------------

### Problem 4: Numpy

Generated a 10x10 `numpy` array with random numbers and slice the array to get the 2nd and 3rd column. Also calculate the average of 6th column using `numpy`.

In [32]:
my_arr = np.arange(1, 101).reshape(10,10)
print(my_arr)
col_2 = my_arr[:, 1, None]
print(col_2)
col_3 = my_arr[:, 2, None]
print(col_3)
avg_col_6 = np.average(my_arr[:, 5, None])
print(avg_col_6)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]
 [62]
 [72]
 [82]
 [92]]
[[ 3]
 [13]
 [23]
 [33]
 [43]
 [53]
 [63]
 [73]
 [83]
 [93]]
51.0


----------------------------------------------------------------

##### That's it! We look forward to seeing you in class!